- package.json
- src/operations/SnapshotEditor.ts
- src/util/collection.ts
- src/util/index.ts
- src/util/primitive.ts
- src/util/references.ts
- src/util/tree.ts
- test/helpers/graphql.ts
- test/unit/operations/write.ts
- yarn.lock
This fills in the logic for writing to the cache, supporting _basic_ cases:
* Adding new nodes to a snapshot
* Editing values within existing nodes
* Normalized references between nodes
It adds _new_ behavior beyond the existing Apollo cache:
* Orphaned nodes are garbage collected.
* Payload values will merge with existing nodes, _even if they don't specify an `id`_. (may be controversial)
---
Next steps (not necessarily in order):
* Support for writing parameterized edges (and preprocessing selection sets to make that efficient)
* Support for reads (validating selection set, including parameterized edges)
* Wire up any missing pieces in order to support the new Apollo `Cache` API.
> Basic graph edits

- scripts/test:unit:coverage.sh
- src/apollo/util.ts
- src/operations/read.ts
- src/schema.ts
- src/util/ast.ts
- test/env/unit.ts
- test/helpers/graphql.ts
- test/helpers/index.ts
- test/unit/operations/write.ts
- test/unit/util/ast.ts
Builder that parses a GraphQL document, turning it into an lookup map to determine which fields of a query are parameterized edges.
This'll be used by `SnapshotEditor` when persisting results from queries with parameterized edges, as well as by `read` when determining which nodes need to be made into views on top of underlying data.
This also refactored `Query` to pass around a complete GraphQL document, rather than just the selection set.  We need the document to look up fragment definitions.
Note that there is a lot of room for improvement here (e.g. memoizing by query, and/or by fragment)
> Parameterized edge map

- src/NodeSnapshot.ts
- src/operations/SnapshotEditor.ts
- src/util/ast.ts
- src/util/collection.ts
- src/util/references.ts
- src/util/tree.ts
- test/unit/operations/write.ts
These are a bit tricky to understand at first glance:
* Whenever we encounter a parameterized edge in a response payload, we create a new NodeSnapshot to hold the value of that edge (for its particular set of arguments)
* That NodeSnapshot will have an incoming reference from its container, _with no path_ (the path is encoded in its id, and we do not want it to modify the containing node).
* We allow these snapshots to _directly_ reference other nodes (e.g. have outgoing references with an `[]` path)
> Write support for parameterized values

- src/operations/SnapshotEditor.ts
- src/util/tree.ts
- test/unit/operations/write.ts
We weren't properly passing the edge map to other nodes when walking them (see tracking `edges` in the walk nodes).
This allows us to nest parameterized edges within arbitrary nodes
> Support parameterized edges nested within other edges

- scripts/test:unit.sh
- src/operations/SnapshotEditor.ts
- src/operations/read.ts
- src/util/tree.ts
- test/unit/operations/read.ts
- test/unit/operations/write.ts
This fills in the guts to satisfy our reads:
* Fetches straight values from the cache.
* Checks whether the cache satisfies the selection set of the requester.
* Overlays parameterized values on top of the results (via `Object.create`)
* Collects the set of node ids selected by the query
---
I'm not particularly happy with how `_overlayParameterizedValues` shook out.  There's been a lot of semi-repetitive tree walking, and there's likely opportunity for abstraction; but not clear how to do it without really ratcheting up complexity
> Read support

- src/operations/read.ts
- test/unit/operations/read.ts
If they had an id, we were not resetting the path to take that into account
> Fix support for arrays of items directly inside parameterized edges

- src/NodeSnapshot.ts
- src/operations/read.ts
- src/util/references.ts
- test/unit/operations/read.ts
* We weren't treating `null`s as present for `complete`
* Several bugs related to `null` values partway down a paramterized path
> Fix several issues with edge walking

- package.json
It's breaking regular installs:
```
> apollo-cache-hermes@0.2.0-alpha postinstall <project>/node_modules/apollo-cache-hermes
> node ./scripts/postinstall.js
module.js:471
throw err;
^
Error: Cannot find module '<project>/node_modules/apollo-cache-hermes/scripts/postinstall.js'
```
> Drop the postinstall for now

- src/operations/read.ts
- test/unit/operations/read.ts
We weren't properly finding the entity they referenced when building paths.
> Fix queries with parameterized edges that have direct references, and nested edges.

- src/apollo/ApolloQueryable.ts
This turns out to be Apollo's current behavior; we had the semantics wrong
> Throw on ApolloQueryable#readQuery

- src/Cache.ts
- src/CacheTransaction.ts
- src/DynamicField.ts
- src/OptimisticUpdateQueue.ts
- src/Queryable.ts
- src/apollo/ApolloQueryable.ts
- src/apollo/util.ts
- src/context/CacheContext.ts
- src/nodes/EntitySnapshot.ts
- src/nodes/NodeSnapshot.ts
- src/nodes/ParameterizedValueSnapshot.ts
- src/nodes/clone.ts
- src/operations/SnapshotEditor.ts
- src/operations/read.ts
- src/operations/write.ts
- src/primitive.ts
- src/schema.ts
- src/util/ast.ts
- src/util/primitive.ts
- src/util/tree.ts
- test/helpers/graphql.ts
- test/unit/context/CacheContext/entityIdForNode.ts
- test/unit/context/CacheContext/entityTransformation.ts
- test/unit/operations/read/cyclicReferences.ts
- test/unit/operations/write/editValues.ts
We should be handling JSON-serializable types…
* …when given a payload from the server
* …from Apollo when writing values
* …when storing values
* …when returning values
> Assert JSON-serializable types where we can

- src/util/references.ts
- test/unit/operations/write/duplicateReferences.ts
When we receive a payload that contains duplicated reference edits (e.g. duplicate subgraphs), ensure we handle it properly.
> Handle duplicated reference updates (arrays, nested, etc)

- src/DynamicField.ts
- src/context/CacheContext.ts
- src/context/QueryInfo.ts
- src/operations/SnapshotEditor.ts
- src/operations/read.ts
- src/schema.ts
- src/util/tree.ts
- test/unit/DynamicField/expandVariables.ts
- test/unit/operations/write/parameterizedFields.ts
Fixes #85 
We now have two "kinds" of `DynamicField`s - those with `VariableArgument`s in their arguments, and those without.  The result of parsing the AST yields (potentially) fields with variables.  
However, when parsing a query (`CacheContext#parseQuery`), we immediately substitute in the values for those variables, to minimize work when reading/writing.  This also allows us to trivially support optional & default field arguments
> Expand variables at query parse time, and support for optional/default arguments

- .circleci/config.yml
Drop the workspace and use caches instead:
* Can now rebuild individual steps
* Each step does minimal work
> Use a cache of code between workflow steps

- src/Cache.ts
- src/CacheTransaction.ts
- src/context/CacheContext.ts
- src/context/QueryInfo.ts
- src/operations/SnapshotEditor.ts
- src/operations/read.ts
We've been seeing a few cases where we've written a payload to the cache, but then had it marked incomplete when immediately read.
This should help to track those cases down (and also recover from them)
> Track all queries we've previously written, and ensure that they come back as complete

- package.json
- src/operations/SnapshotEditor.ts
Since TypeScript 2.5 came out, the `^2.4.2` installs it by default. With that version, there was a TypeError for calling `Object.keys` on a possible non object. This force casts the type def for it.
> update typescript and fix error

- .vscode/launch.json
- src/nodes/NodeSnapshot.ts
- src/operations/SnapshotEditor.ts
- src/util/references.ts
- test/unit/operations/write/parameterizedFields.ts
* Makes `path` a required property on all references
* We now inspect the kind of node being traversed when rebuilding references (only rebuild entity references!)
* Fixes garbage collection of parameterized edges contained within arrays
> Garbage collect parameterized edges in nodes that are removed from arrays

- src/operations/SnapshotEditor.ts
- test/unit/operations/write/editValues.ts
- test/unit/operations/write/orphans.ts
- test/unit/operations/write/parameterizedFields.ts
Our previous logic was removing the wrong references from arrays that also change their order (such as shifting the first value off of an array).
This removes our logic for GCing orphaned array references - prefer leaking over wonky behavior
> Let orphaned array references leak for now

- src/operations/SnapshotEditor.ts
This is a slight perf optimization for optimistic updates - we move the inbound reference rewriting to commit(), so that it only occurs once when we merge multiple payloads in the same transaction.
> Refactor SnapshotEditor a bit

- src/Cache.ts
- src/context/CacheContext.ts
- src/operations/read.ts
It turns out it's legitimate for a previously written query to transition from complete to incomplete.  For example:
```json
{"foo": null}
```
satisfies `{ foo { bar } }`
```json
{"foo": {"fizz": 123} }`
```
no longer satisfies `{ foo { bar } }`
> Drop write tracking

- src/ParsedQueryNode.ts
- src/context/CacheContext.ts
- test/unit/ParsedQueryNode/directives.ts
The checks for unused variables were throwing for variables used exclusively within directives.
Tests included, non-breaking.
> Ensure variables used in directives are collected

- src/operations/read.ts
- src/util/tree.ts
- test/unit/operations/read/incompletePayload.ts
`walkOperation` and the general computation of read completeness were broken when it concerned complex fields with alias names. This patches a couple of gaps.
Tests included, non-breaking.
> Fix field aliases when computing read completeness

- scripts/test-unit.sh
This is to set maximum number of workers when running the unit test. I was doing this because I keep running into out-of-memory error. But `--maxWorkers` and `--runInBands` don't work together so we have to check if we are in debugging or not
> Only set --maxWorkers when we are NOT debugging

- package.json
2.6 is breaking us, and we've seen point releases break in the past
> Lock TS on it's Y-version

- src/Cache.ts
- src/CacheSnapshot.ts
- src/CacheTransaction.ts
- src/apollo/Hermes.ts
- src/context/CacheContext.ts
- test/unit/context/CacheContext/entityUpdaters.ts
- test/unit/context/CacheContext/onChange.ts
- test/unit/context/CacheContext/onChangeWithError.ts
Add onChange to cache configuration API to allow users to perform tasks such as dispatch redux action when there is a change in the cache or log the update etc.
> Add onChange callback in cache configuration

- src/Cache.ts
- src/ParsedQueryNode.ts
- src/context/CacheContext.ts
- src/context/ConsoleTracer.ts
- src/context/Tracer.ts
- src/operations/SnapshotEditor.ts
- src/operations/extract.ts
- src/operations/read.ts
- src/operations/write.ts
- test/helpers/context.ts
- test/unit/Cache/transactions.ts
- test/unit/context/CacheContext/onChangeWithError.ts
This allows us to instrument the cache at various points, and callers can use it for logging, performance monitoring, APM, etc.
> Move logging into a formal tracing interface

- src/index.ts
So that it can be consumed directly and/or extended
> Export ConsoleTracer as part of the public API

- package.json
- src/apollo/Queryable.ts
- src/errors.ts
- src/index.ts
Apollo cache hermes throws and error with message `read not satisfied by the cache.` upon incomplete read. As a consumer I want to identify this error as a specific error instance and ignore them. The best way to do this is check error instance of. So this change throws a new `UnsatisfiedCacheError` and exposes it as well as other errors so I can sanity check them on my app.
> Specific error being thrown for partial read 

- src/GraphSnapshot.ts
- src/operations/SnapshotEditor.ts
This was preventing us from benefiting from read caching in development mode.  Also errors
> Freeze snapshot values, but not the read cache

- README.md
Came across some bugs as I was working on testing for `apollo-cache-persist`. Sorry prettier messed up the diff, the two main things I fixed were:
- fixing the import statement for lodashGet
- fixing the readme for Apollo Client initialization
> Fixed import & client initialization docs

- src/operations/read.ts
- src/util/tree.ts
This PR  is trying to make thing more consistent between read/write operation. We usually walk  ParsedQueryNode when doing operation except when we verify the read result.
> walk ParsedQueryNode instead of documentNode in read operation

- src/CacheTransaction.ts
- test/unit/Cache/transactions.ts
Prior to this change, if you had multiple optimistic transactions, you'd only see the latest one reflected in the optimistic snapshot. This one-line change fixes the issue and includes a test.
> Fix optimistic transactions

- src/operations/index.ts
- src/operations/migrate.ts
- src/util/references.ts
- test/unit/operations/migrate/entitiesReferencedInParameterizedValue.ts
- test/unit/operations/migrate/entityMigrations.ts
- test/unit/operations/migrate/exceptionCases.ts
Support for a new operation, `migrate()`, which takes a `migrationMap` and migrates entities in the cache from their old shape. Useful in upgrading the persisted data following a `restore`.
> add cache migrate support and tests

- src/Cache.ts
- src/apollo/Hermes.ts
- src/index.ts
- src/operations/index.ts
- test/unit/Apollo/persistenceRoundTrip.ts
- test/unit/Cache/deserializeWithMigration.ts
- test/unit/Cache/serializationWithPruning.ts
This wires up the `prune` and `migration` operation PR-ed previously to `Cache` and expose migration functionality on `Hermes`' interface. With tests, of course. 😄
> Expose migration on Hermes

- src/operations/extract.ts
@jamesreggio  ran into an infinite recursion during extract. This is occur inside `isSerializable` function. This is possible a result of circular reference in data. Before we are trying to instrument any fix of circular reference which is not trivia. We will catch the stack overflow error to get more context
> Try catch stackoverflow in isSerializable of extract

- src/util/references.ts
getIndexOfGivenReference() can return -1 if there are duplicate referenceEdits in the transaction (which can happen if the same entity is returned at different points within the payload).
[].splice(-1, 1) removes the last item from the array, which was leading to general mayhem in the wild. Hopefully this fixes some heisenbugs for everyone.
(I wasn't able to craft a test to reproduce this.)
> Fix a bug that wrecks havoc upon reference bookkeeping

- src/CacheTransaction.ts
- test/unit/Cache/transactions.ts
When `transaction.rollback` was called, the resulting optimistic snapshot still included the rolled-back snapshot. The reason was `transaction._buildOptimisticSnapshot` was using the current `optimisticQueue` instead of the new one generated after removing the rolled-back update from the queue. Added failing test for the bug.
> Fix optimistic updates not getting rolled back

- src/apollo/Transaction.ts
Catch error from `readFragment` (this is based on my understanding of this document
https://www.apollographql.com/docs/react/advanced/caching.html#readfragment
particularly 
> If a todo with that id does not exist in the cache you will get null back. If a todo of that id does exist in the cache, but that todo does not have the text field then an error will be thrown.
> Catch an error from ReadFragment and keep going

- src/operations/read.ts
- test/unit/operations/read/parameterizedFields.ts
The test demonstrates the problem, but basically, if you have two nested, parameterized fields without any simple (non-parameterized) fields on the intermediate node, the intermediate node will be written into the snapshot with `null` for its `data`, which will short-circuit the dynamic value overlay walk.
The `nextContainerId` and `nextPath` juggling is necessary to ensure that arguments are affixed in the correct order as we build the path to deeper nodes. Without it, the next `OverlayWalkNode` would simply incorporate the `fieldName` of the parent, and its arguments would be lost.
> Fix read traversal

- src/context/CacheContext.ts
Without this, Hermes will think it's in a development environment even if you pass --mode production via webpack
(Webpack is looking for the literal string `process.env.NODE_ENV` via DefinePlugin)
> Fix how we detect NODE_ENV so that webpack can swap it out

- test/unit/operations/write/fragment/overlappingFragmentFields.ts
Per a Slack conversation with @nevir.
This should ideally work when #153 is resolved.
> Add (broken) test for data loss when unrelated fragments have overlapping fields

- src/Cache.ts
- src/CacheTransaction.ts
- src/util/collection.ts
- test/unit/Apollo/writeFragment/writeThenRead.ts
- test/unit/Cache/deserializeWithMigration.ts
- test/unit/Cache/readCacheCarryForward.ts
Closes #362
This adds a few changes on top of #362:
* Short circuits if baseline and optimistic are the same snapshot
* Micro-optimization to always iterate the smallest set when looking for intersections
* Moar tests!
> Tweaks to #362

- src/apollo/Transaction.ts
Originally `updateListOfReference` is designed to only update list of reference directly off parameterized field
With following GraphQL and payload
```
parameterizedFieldToModify(modify:true) {
id
status
}
```
```
parameterizedFieldToModify: [
{ id: 1, status: 'neededModified' },
{ id: 2, status: 'noNeedForModified' }
]
```
This PR will allow users to be able to make modification at parameterized field in which either object and array is hanging off
```
parameterizedFieldToModify(modify:true) {
edges {
id
status
}
}
```
```
parameterizedFieldToModify: {
edges: [
{ id: 1, status: 'neededModified' },
{ id: 2, status: 'noNeedForModified' }
],
}
```
**Todo**
> Allow object at parameterized field to be update

- src/operations/migrate.ts
- test/unit/operations/migrate/exceptionCases.ts
Removed unnecessary check preventing migration adding reference fields to existing entity.
e.g. adding
```
citation {
id
citationNumber
}
```
to `fullArticle` fragment.
The reference field check prevents the valid migrations like:
```
_entities: {
Article: {
citation: previous => previous || null
}
}
```
from moving forward. 😢
> Allow reference field to be migrated

- src/Cache.ts
- src/operations/QueryObserver.ts
- src/operations/read.ts
- test/unit/Cache/readCacheCarryForward.ts
- test/unit/operations/read/cyclicReferences.ts
- test/unit/operations/read/noDynamicFeatures.ts
- test/unit/operations/read/parameterizedFields.ts
No more walking entire one-off queries to collect nodeIds
> Only crawl nodeIds for observed queries

- .vscode/launch.json
- package.json
- src/Cache.ts
- src/context/CacheContext.ts
- src/operations/QueryObserver.ts
- src/operations/read.ts
- test/unit/Cache/readCacheCarryForward.ts
By default, strict mode is enabled. If you disable it:
* The cache will assume that any complete read will stay complete. Whether this is safe is application-dependent. Docs forthcoming.
* This allows us to skip the walk of results for any observed query, which is the majority of Hermes' time spent.
> Expose strict mode

- src/ParsedQueryNode.ts
- test/unit/ParsedQueryNode/fragments.ts
- test/unit/operations/write/fragment/nestedValueUsingInlineFragment.ts
Related to #153.
These simple changes add basic support for inline fragments (also known as union queries).
These changes were enough to make our app work, which makes heavy use of inline fragments and union types. Obviously, tests need to be written, but I'm not certain I'll have time to get to that any time soon, so I'm leaving my WIP here in case anybody would like to take over.
The only concern I have about this implementation is that I'm not inserting `nulls` per @nevir's guidance:
> When writing fields, any union field present in the payload should be written normally (except if not present, nulls shouldn't be inserted)
> Add support for inline fragments

- src/operations/SnapshotEditor.ts
Extending the error message for mismatches in id existence within payload.  We hit this error without much context into the actual cause.
> Extended error message for mismatches in id existence within payload

- src/context/CacheContext.ts
- src/operations/SnapshotEditor.ts
- test/unit/Apollo/writeFragment/errorMissingTypename.ts
- test/unit/context/CacheContext/addTypeName.ts
✔ Write a summary
Add warning around missing __typename in fragment payload. See #412. This is my attempt to add a warning around this condition. Note that the warning is only emitted if verbose logging is enabled so I'm not sure how helpful it'll be.
✔ Tests!
N/A
✔ Bump the version if needed
N/A
> add warning around missing __typename in fragment payload

- src/operations/migrate.ts
- test/unit/operations/migrate/entitiesWithParameterizedFields.ts
✔ Write a summary
Adds ability to migrate parametrized fields by copying the data from same path, currently we only support migrating parametrized fields to a default value
✔ Tests!
Added a test for this particular scenario and we already have good coverage in this code path
✔ Bump the version if needed
* Adding a new, backwards-compatible, feature?  Sweet!
Please increment the Y version in package.json.
> Adds ability to migrate parametrized field by copying from same path

- package.json
- src/Cache.ts
- src/CacheTransaction.ts
- src/ParsedQueryNode.ts
- src/Queryable.ts
- src/apollo/Hermes.ts
- src/apollo/Queryable.ts
- src/apollo/Transaction.ts
- src/apollo/util.ts
- src/context/CacheContext.ts
- src/operations/SnapshotEditor.ts
- src/util/ast.ts
- src/util/index.ts
- src/util/references.ts
- src/util/store.ts
- test/env/base.ts
- test/unit/Cache/watchParameterizedFields.ts
- test/unit/Cache/watchStaticFields.ts
- test/unit/context/CacheContext/entityTransformation.ts
- test/unit/context/CacheContext/entityUpdaterOptimisticChange.ts
- test/unit/util/ast/selectionSetIsStatic.ts
- tsconfig.json
- yarn.lock
The main purpose of this change is to add support for the v3 apollo client. The biggest change affecting Hermes in version 3 is the consolidation of the apollo packages into one `@apollo/client`package. Some utilities from the deprecated `apollo-utilities` package have been removed, and the rest are now accessible via `@apollo/client/utilities`. For the utility methods that were removed, I copied the original implementations from `apollo-utilities` into Hermes. The `isEqual` utility is an exception, as the original implementation was just an alias to `@wry/equality`. For that utility, I just added a dependency to that package. 
There are a couple of changes in particular that I would like careful review:
- ApolloQueryable now *extends* ApolloCache instead of just implementing its …
> Update apollo client to v3 and TypeScript to latest

- src/operations/read.ts
- test/unit/operations/read/noDynamicFeatures.ts
- test/unit/operations/read/parameterizedFields.ts
Hermes is not able to resolve parameterized nodes that are nested in a multi-dimensional array. Writes to the cache in this scenario is correct, but on reads, we were not calculating the path of the parameterized nodes correctly. This happens because multi-dimensional arrays were not considered when [traversing children](https://github.com/convoyinc/apollo-cache-hermes/blob/3d44bd1c01ab683531a0ab2fd3599571ba715eb3/src/operations/read.ts#L176). This change looks for the GraphQL objects at any depth.
> Parameterized entities with multi dimensional arrays

- src/Cache.ts
✔ Write a summary
Throw UnsatisifiedCacheError instead of a generic Error on cache restore when the verifyQuery cannot be satisfied
This makes more sense because the error can be handled appropriately. A generic error could be something else going wrong.
✔ Tests!
Tests are already written for this case that it throws an error
✔ Bump the version if needed
Just fixes a bug
> Throw UnsatisifiedCacheError on cache restore instead of generic error

- package.json
- src/apollo/Hermes.ts
`Hermes` extends `ApolloQueryable<GraphSnapshot>` which in turn extends `ApolloCache<GraphSnapshot>` in which the method `restore` is defined as returning `ApolloCache<GraphSnapshot>`. We return `this` in our implementation, and while `Hermes` is a valid `ApolloCache<GraphSnapshot>`, we should be clear that we are returning `Hermes`. This would then let consumers of `Hermes` use `Hermes` specific methods on the result of `hermes.restore(...)`.
As this only changes a type no tests are needed.
> Make Hermes.restore return Hermes instead of the superclass type
