convoyinc/apollo-cache-hermes

docs/ARCHITECTURE.md, docs/MOTIVATION.md
This doc provides some context around the challenges the existing cache implementations face.  
Next doc will be an `ARCHITECTURE.md` that details the approach we're taking (framed by the points noted in `MOTIVATION.md`).  During that, I'll probably be porting over pieces of our new cache implementation, as well.
=> Document the motivation behind this cache

src/util/collection.ts, test/unit/util/collection.ts
From the other repo; unchanged.
=> Port over lazyImmutableDeepSet

test/unit/operations/write.ts
This _theoretically_ gives Jest/Jasmine the ability to only run a block for tests that care about it (when scoping to a specific test, etc).  However, jest seems to run them all regardless, when scoping to a particular test via its runtime filtering
=> Migrate test subjects to beforeAll blocks

docs/Architecture.md
Fix broken link on mergePayload to SnapshotEditor ;)
=> Fix broken in link in Architecture.md

src/operations/read.ts, test/unit/operations/read.ts, test/unit/operations/write.ts
Explicit tests for 'em.  So far, it looks like we're all good here - but there are probably some cases I'm missing.
=> Full support for cyclic references

package.json, src/Cache.ts, src/apollo/ApolloCache.ts, src/apollo/ApolloQueryable.ts, src/apollo/index.ts, src/index.ts, src/schema.ts, src/util/references.ts, test/unit/index.ts, yarn.lock
Small changes to make things easier to plug in to apollo 2.0.
=> Make things work with apollo 2.0

src/operations/read.ts, test/unit/operations/read.ts
There's probably a better approach (see the TODO I added)
=> Partial fix to empty entity snapshots

src/apollo/ApolloQueryable.ts
Not confident that this is the correct change; but it does unblock the benchmark.
=> Don't throw in diffQuery

src/Cache.ts, src/CacheContext.ts, src/CacheTransaction.ts, src/OptimisticUpdateQueue.ts, src/apollo/ApolloCache.ts, src/apollo/util.ts, src/context/CacheContext.ts, src/context/QueryInfo.ts, src/context/index.ts, src/operations/QueryObserver.ts, src/operations/SnapshotEditor.ts, src/operations/read.ts, src/operations/write.ts, src/schema.ts, test/unit/operations/read.ts, test/unit/operations/write.ts
Cuts down on a lot of duplicate work
=> Parse & memoize queries

src/GraphSnapshot.ts, src/context/CacheContext.ts, src/operations/read.ts
=> Memoize reads

src/operations/SnapshotEditor.ts, test/unit/operations/write.ts
…and slap a big fat TODO on it to express how bad this approach is.
=> Handle empty objects

src/context/CacheContext.ts, src/operations/SnapshotEditor.ts, test/unit/operations/write.ts
=> Better handling for sparse arrays

src/CacheTransaction.ts, src/context/CacheContext.ts, src/operations/SnapshotEditor.ts, src/operations/read.ts, src/util/ast.ts, src/util/tree.ts, test/unit/context/QueryInfo.ts, test/unit/operations/write.ts
Hopefully a bit easier to read now.
=> Null assertion & other type style cleanup

docs/Terminology.md, src/GraphSnapshot.ts, src/context/QueryInfo.ts, src/nodes/index.ts, src/operations/SnapshotEditor.ts, src/operations/read.ts, src/util/ast.ts, src/util/collection.ts, src/util/references.ts, src/util/tree.ts, test/unit/context/QueryInfo.ts, test/unit/operations/read.ts, test/unit/operations/write.ts, test/unit/util/ast.ts
=> Support for alias

docs/Terminology.md, src/context/CacheContext.ts, src/operations/SnapshotEditor.ts, test/unit/context/CacheContext.ts, test/unit/context/entityTransformation.ts
=> Fix #55: Support Entity Transformed

src/context/CacheContext.ts
=> EntityTransformer only uses one arg

src/Cache.ts, src/context/CacheContext.ts, test/helpers/context.ts, test/unit/Cache/transactions.ts
Log them out and roll back, but don't throw
=> Soft-fail on errors in transactions

.vscode/launch.json, src/operations/read.ts, test/unit/context/CacheContext/entityTransformation.ts
This is a fix to get nacho-dashboard to use entityTransformer.
=> Copy Prototype when read

.circleci/config.yml, package.json
=> Bump to 0.3

src/context/CacheContext.ts, src/operations/read.ts, test/unit/operations/read/redirects.ts
Resolves #47 (also see [design doc](https://docs.google.com/document/d/1x2tQWTJbchfoU8i56NTxwsnqnpDJMQvPVKQ5JiHbSco/))
Note that this only works for parameterized fields, and only allows you to point to entities
=> Resolver redirects

docs/Design Exploration.md
=> Update Design Exploration.md

test/unit/operations/write/basic/multidimensionalReferencesArray.ts, test/unit/operations/write/basic/multidimensionalValuesArray.ts
Add write test for multi dimensional array
=> Add write test for multidimensional array

src/operations/extract.ts
Add missing comment from PR #187
=> Adddress PR #187: add comment

src/operations/restore.ts
This is so that I can start writing an end-to-end tests of serialization through the cache interface!
=> [Serialization] Update restore function signature

package.json, src/ParsedQueryNode.ts, src/operations/SnapshotEditor.ts, src/operations/read.ts, src/schema.ts, src/util/primitive.ts, src/util/tree.ts
Use specific lodash packages to cut down on dependency sizes
=> Fix use of lodash

package.json, src/ParsedQueryNode.ts, src/operations/SnapshotEditor.ts, src/operations/read.ts, src/schema.ts, src/util/primitive.ts, src/util/tree.ts
And lodash.isarray is deprecated.
=> Go back to Array.isArray; we expect a modern env

test/unit/operations/extract/parameterizedFields/topLevelValueWithNestedParameterizedReferenceInArray.ts
=> Enable extract tests

test/unit/operations/extract/parameterizedFields/topLevelParameterizedValueNull.ts, test/unit/operations/extract/parameterizedFields/topLevelValueWithDeeplyNestedParameterizedReferenceInArray.ts
=> Add test for parameterized extract tests

src/context/CacheContext.ts
Should have been done via #177
=> Truly drop the [Cache] logging prefix

src/context/ConsoleTracer.ts
This makes it easier to work with in environments like node (or RN)
=> Emulate console groups if not present

.eslintrc.yml
=> Disable import/no-unresolved temporarily

package.json, src/CacheTransaction.ts, src/GraphSnapshot.ts, test/unit/operations/write/basic/falsyValues.ts, test/unit/operations/write/basic/multidimensionalReferencesArray.ts, test/unit/operations/write/basic/multidimensionalValuesArray.ts, test/unit/operations/write/parameterizedFields/orphanValueInArrayWithNestedParameterizedReferences.ts, test/unit/operations/write/parameterizedFields/updateParameterizedReferencesInArray.ts, tsconfig.json
=> Typescript 2.6

src/OptimisticUpdateQueue.ts
It's hard.
Also, @nevir is writing this
=> Boolean logic is hard, guys

src/ParsedQueryNode.ts, src/index.ts, src/util/ast.ts, test/unit/util/ast/selectionSetIsStatic.ts, typings/jest/index.d.ts
The intention here is to provide a method that can be used to assert on specific queries or fragments, so you can ensure that they are taking the fast path
=> Expose a selectionSetIsStatic helper

src/apollo/Queryable.ts
=> Stub out ApolloCache's witeData method so we can build again

.circleci/config.yml
Faster installs; less churn, hopefully.
=> Pull in past deps installs for delta updates

.circleci/config.yml, package.json, yarn.lock
See https://github.com/greenkeeperio/greenkeeper-lockfile/pull/118
=> Fix greenkeeper lockfile support

src/apollo/Transaction.ts, src/util/primitive.ts
Add more context when logging an error
=> Add more context when logging

package.json, src/Cache.ts, src/operations/QueryObserver.ts, test/unit/Cache/watchParameterizedFields.ts, test/unit/Cache/watchStaticFields.ts, test/unit/jest.json
=> Add tests for #244 and bump to 0.6

src/apollo/Transaction.ts, yarn.lock
Cherry-pick of the change in this PR #374 to our custom branch
=> [Cherry-pick] Port the change form master into our custom branch

src/apollo/Transaction.ts, yarn.lock
Reverts convoyinc/apollo-cache-hermes#376
=> Revert "[Cherry-pick] Port the change form master into our custom branch"

yarn.lock
=> Add integration hashes to yarn.lock

src/errors.ts, test/unit/errors/CacheError.ts
So we can link extend information about how to deal with specific errors
=> Allow errors to include an info URL

docs/errors/InvalidEnvironmentError.md, package.json, src/environment.ts, src/errors.ts, src/index.ts, test/unit/errors/HermesCacheError.ts
=> Detect and blow up on invalid environments

README.md
=> I think we're beyond an experiment - been in production for over a year.

package.json, scripts/test-unit-coverage.sh, yarn.lock
( [PR Etiquette at Convoy](https://docs.google.com/presentation/d/18OWgxz6UKRFtXWTctDG-Pv3imWzhPqkZpmW14-mMnkY/edit#slide=id.g3b3fb0e229_0_625) )
What changes are in this PR?
- remove codecov
Why do these changes need to be done? Include any links to TP, Clubhouse, Slack, etc
- we no longer use codecov and have migrated to coveralls for t1/t2 services
=> kill codecov

.circleci/config.yml, yarn.lock
✔ Write a summary
Attempt to fix publishing by switching to Artifactory
✔ Tests!
Untestable without actually trying to publish
=> Attempt to fix publishing by switching to Artifactory

.circleci/config.yml
Continuing https://github.com/convoyinc/apollo-cache-hermes/pull/459
=> Try to use a different release step

.circleci/config.yml
Continuing https://github.com/convoyinc/apollo-cache-hermes/pull/460
=> Need the right version of circleci config?

.circleci/config.yml, package.json
Continuing https://github.com/convoyinc/apollo-cache-hermes/pull/461
=> Bypass (broken?) release script

.circleci/config.yml, .eslintrc.yml, .gitignore, package.json, src/Cache.ts, src/apollo/Hermes.ts, src/apollo/Queryable.ts, src/operations/extract.ts, src/util/store.ts, test/unit/ParsedQueryNode/expandVariables.ts, yarn.lock
Upgrade dependencies required to get us to Apollo Client 3.1.3
=> Upgrade dependencies required to get us to Apollo Client 3.1.3
